export enum AccountTransactionType {
  BUY = 'BUY',
  DEPOSIT = 'DEPOSIT',
  DIVIDEND = 'DIVIDEND',
  INTEREST_INCOME = 'INTEREST_INCOME',
  LONG_TERM_CAPITAL_GAIN = 'LONG_TERM_CAPITAL_GAIN',
  SELL = 'SELL',
  SHORT_TERM_CAPITAL_GAIN = 'SHORT_TERM_CAPITAL_GAIN',
  TRANSFER = 'TRANSFER',
  WITHDRAW = 'WITHDRAW',
}
