export enum AccountType {
  BOND = 'BOND',
  CREDIT_CARD = 'CREDIT_CARD',
  CRYPTO = 'CRYPTO',
  DEPOSIT = 'DEPOSIT',
  EQUITY = 'EQUITY',
  LOAN = 'LOAN',
  MONEY_MARKET = 'MONEY_MARKET',
  MORTGAGE = 'MORTGAGE',
  STOCK = 'STOCK',
}
